name: Daily Task

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Verifique se as versões dos pacotes são compatíveis com Python 3.12.

    - name: Execute script
      run: python main.py
